# Generated by Django 5.2.6 on 2025-10-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="phone",
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="client",
            name="reference_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
